seed: 0
codebase_version: 1.0
headless: false
num_envs: 1
auto_load_latest: false
checkpoint: null
project_name: G1TestDeploy
experiment_name: G112dof_loco_IsaacGym
base_dir: logs
timestamp: ${now:%Y%m%d_%H%M%S}
experiment_dir: ${base_dir}/${project_name}/${timestamp}-${experiment_name}-${log_task_name}-${robot.asset.robot_type}
save_dir: ${experiment_dir}/.hydra
force_flat_terrain: false
use_wandb: false
log_task_name: locomotion
sim_type: isaacgym
env_spacing: 20
output_dir: ${experiment_dir}/output
eval_overrides:
  headless: false
  num_envs: 1
  auto_load_latest: false
  use_wandb: false
  env:
    config:
      max_episode_length_s: 100000
algo:
  _target_: humanoidverse.agents.ppo.ppo.PPO
  _recursive_: false
  config:
    num_learning_epochs: 5
    num_mini_batches: 4
    clip_param: 0.2
    gamma: 0.99
    lam: 0.95
    value_loss_coef: 1.0
    entropy_coef: 0.01
    actor_learning_rate: 0.001
    critic_learning_rate: 0.001
    max_grad_norm: 1.0
    use_clipped_value_loss: true
    schedule: adaptive
    desired_kl: 0.01
    num_steps_per_env: 24
    save_interval: 100
    load_optimizer: true
    init_noise_std: 0.8
    num_learning_iterations: 5000
    init_at_random_ep_len: true
    eval_callbacks: null
    module_dict:
      actor:
        input_dim:
        - actor_obs
        output_dim:
        - robot_action_dim
        layer_config:
          type: MLP
          hidden_dims:
          - 512
          - 256
          - 128
          activation: ELU
      critic:
        type: MLP
        input_dim:
        - critic_obs
        output_dim:
        - 1
        layer_config:
          type: MLP
          hidden_dims:
          - 512
          - 256
          - 128
          activation: ELU
env:
  _target_: humanoidverse.envs.locomotion.locomotion.LeggedRobotLocomotion
  _recursive_: false
  config:
    experiment_name: ${experiment_name}
    num_envs: ${num_envs}
    headless: ${headless}
    simulator: ${simulator}
    save_rendering_dir: null
    ckpt_dir: null
    robot: ${robot}
    domain_rand: ${domain_rand}
    rewards: ${rewards}
    terrain: ${terrain}
    obs: ${obs}
    env_spacing: 5.0
    max_episode_length_s: 100000
    normalization:
      clip_actions: 100.0
      clip_observations: 100.0
    termination:
      terminate_when_close_to_dof_pos_limit: false
      terminate_when_close_to_dof_vel_limit: false
      terminate_when_close_to_torque_limit: false
      terminate_by_contact: false
      terminate_by_gravity: true
      terminate_by_low_height: false
    termination_scales:
      termination_close_to_dof_pos_limit: 0.98
      termination_close_to_dof_vel_limit: 0.98
      termination_close_to_torque_limit: 0.98
      termination_min_base_height: 0.3
      termination_gravity_x: 0.8
      termination_gravity_y: 0.8
    locomotion_obs_scales:
      lin_vel: 1.0
      ang_vel: 1.0
      dof_pos: 1.0
      dof_vel: 1.0
      humanoid_commands_scale: 1.0
    locomotion_command_ranges:
      lin_vel_x:
      - -1.0
      - 1.0
      lin_vel_y:
      - -1.0
      - 1.0
      ang_vel_yaw:
      - -1.0
      - 1.0
      heading:
      - -3.14
      - 3.14
    locomotion_command_resampling_time: 10.0
robot:
  dof_obs_size: 12
  number_of_actions: ???
  self_obs_max_coords: ???
  num_bodies: 13
  algo_obs_dim_dict:
    actor_obs: 45
    critic_obs: 45
  key_bodies:
  - left_ankle_roll_link
  - right_ankle_roll_link
  contact_bodies:
  - left_ankle_roll_link
  - right_ankle_roll_link
  foot_name: ankle_roll_link
  init_state:
    pos:
    - 0.0
    - 0.0
    - 0.8
    rot:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    lin_vel:
    - 0.0
    - 0.0
    - 0.0
    ang_vel:
    - 0.0
    - 0.0
    - 0.0
    default_joint_angles:
      left_hip_yaw_joint: 0.0
      left_hip_roll_joint: 0.0
      left_hip_pitch_joint: -0.1
      left_knee_joint: 0.3
      left_ankle_pitch_joint: -0.2
      left_ankle_roll_joint: 0.0
      right_hip_yaw_joint: 0.0
      right_hip_roll_joint: 0.0
      right_hip_pitch_joint: -0.1
      right_knee_joint: 0.3
      right_ankle_pitch_joint: -0.2
      right_ankle_roll_joint: 0.0
  contact_pairs_multiplier: 16
  num_key_bodies: ${len:${robot.key_bodies}}
  mimic_small_marker_bodies: null
  randomize_link_body_names:
  - pelvis
  - left_hip_yaw_link
  - left_hip_roll_link
  - left_hip_pitch_link
  - left_knee_link
  - right_hip_yaw_link
  - right_hip_roll_link
  - right_hip_pitch_link
  - right_knee_link
  control:
    control_type: P
    stiffness:
      hip_yaw: 100
      hip_roll: 100
      hip_pitch: 100
      knee: 200
      ankle_pitch: 20
      ankle_roll: 20
    damping:
      hip_yaw: 2.5
      hip_roll: 2.5
      hip_pitch: 2.5
      knee: 5.0
      ankle_pitch: 0.2
      ankle_roll: 0.1
    action_scale: 0.25
    isaac_pd_scale: false
    clamp_actions: 1.0
    clip_torques: true
    action_clip_value: 100.0
  asset:
    collapse_fixed_joints: true
    replace_cylinder_with_capsule: true
    flip_visual_attachments: false
    armature: 0.0
    thickness: 0.01
    max_angular_velocity: 1000.0
    max_linear_velocity: 1000.0
    density: 0.001
    angular_damping: 0.0
    linear_damping: 0.0
    disable_gravity: null
    fix_base_link: null
    default_dof_drive_mode: 3
    robot_type: g1_12dof
    urdf_file: g1/${robot.asset.robot_type}.urdf
    usd_file: g1/${robot.asset.robot_type}.usd
    xml_file: g1/${robot.asset.robot_type}.xml
    asset_root: humanoidverse/data/robots
    self_collisions: 1
    filter_ints: null
  actions_dim: 12
  policy_obs_dim: -1
  critic_obs_dim: -1
  num_feet: 2
  right_foot_name: right_ankle_roll_link
  left_foot_name: left_ankle_roll_link
  knee_name: knee_link
  dof_names:
  - left_hip_pitch_joint
  - left_hip_roll_joint
  - left_hip_yaw_joint
  - left_knee_joint
  - left_ankle_pitch_joint
  - left_ankle_roll_joint
  - right_hip_pitch_joint
  - right_hip_roll_joint
  - right_hip_yaw_joint
  - right_knee_joint
  - right_ankle_pitch_joint
  - right_ankle_roll_joint
  upper_dof_names: []
  lower_dof_names:
  - left_hip_pitch_joint
  - left_hip_roll_joint
  - left_hip_yaw_joint
  - left_knee_joint
  - left_ankle_pitch_joint
  - left_ankle_roll_joint
  - right_hip_pitch_joint
  - right_hip_roll_joint
  - right_hip_yaw_joint
  - right_knee_joint
  - right_ankle_pitch_joint
  - right_ankle_roll_joint
  has_torso: false
  has_upper_body_dof: false
  dof_pos_lower_limit_list:
  - -2.5307
  - -0.5236
  - -2.7576
  - -0.087267
  - -0.87267
  - -0.2618
  - -2.5307
  - -2.9671
  - -2.7576
  - -0.087267
  - -0.87267
  - -0.2618
  dof_pos_upper_limit_list:
  - 2.8798
  - 2.9671
  - 2.7576
  - 2.8798
  - 0.5236
  - 0.2618
  - 2.8798
  - 0.5236
  - 2.7576
  - 2.8798
  - 0.5236
  - 0.2618
  dof_vel_limit_list:
  - 32.0
  - 32.0
  - 32.0
  - 20.0
  - 37.0
  - 37.0
  - 32.0
  - 32.0
  - 32.0
  - 20.0
  - 37.0
  - 37.0
  dof_effort_limit_list:
  - 88.0
  - 88.0
  - 88.0
  - 139.0
  - 50.0
  - 50.0
  - 88.0
  - 88.0
  - 88.0
  - 139.0
  - 50.0
  - 50.0
  dof_armature_list:
  - 0.01
  - 0.01
  - 0.01
  - 0.01
  - 0.01
  - 0.01
  - 0.01
  - 0.01
  - 0.01
  - 0.01
  - 0.01
  - 0.01
  dof_joint_friction_list:
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  body_names:
  - pelvis
  - left_hip_pitch_link
  - left_hip_roll_link
  - left_hip_yaw_link
  - left_knee_link
  - left_ankle_pitch_link
  - left_ankle_roll_link
  - right_hip_pitch_link
  - right_hip_roll_link
  - right_hip_yaw_link
  - right_knee_link
  - right_ankle_pitch_link
  - right_ankle_roll_link
  terminate_after_contacts_on:
  - pelvis
  - shoulder
  - hip
  penalize_contacts_on:
  - pelvis
  - shoulder
  - hip
  motion:
    lower_body_link:
    - pelvis
    - left_hip_pitch_link
    - left_hip_roll_link
    - left_hip_yaw_link
    - left_knee_link
    - left_ankle_pitch_link
    - left_ankle_roll_link
    - right_hip_pitch_link
    - right_hip_roll_link
    - right_hip_yaw_link
    - right_knee_link
    - right_ankle_pitch_link
    - right_ankle_roll_link
    - waist_yaw_link
    - waist_roll_link
    - torso_link
    upper_body_link:
    - left_shoulder_pitch_link
    - left_shoulder_roll_link
    - left_shoulder_yaw_link
    - left_elbow_link
    - right_shoulder_pitch_link
    - right_shoulder_roll_link
    - right_shoulder_yaw_link
    - right_elbow_link
    - left_hand_link
    - right_hand_link
    - head_link
    pelvis_link: pelvis
    base_link: torso_link
    hips_link:
    - left_hip_pitch_link
    - left_hip_roll_link
    - left_hip_yaw_link
    - right_hip_pitch_link
    - right_hip_roll_link
    - right_hip_yaw_link
terrain:
  static_friction: 1.0
  dynamic_friction: 1.0
  restitution: 0.0
  mesh_type: plane
  horizontal_scale: 0.1
  vertical_scale: 0.005
  border_size: 40
  curriculum: false
  measure_heights: false
  measured_points_x:
  - 0.0
  measured_points_y:
  - 0.0
  selected: false
  terrain_kwargs: null
  max_init_terrain_level: 9
  terrain_length: 8.0
  terrain_width: 8.0
  num_rows: 10
  num_cols: 20
  terrain_types:
  - flat
  - rough
  - low_obst
  - smooth_slope
  - rough_slope
  terrain_proportions:
  - 0.2
  - 0.6
  - 0.2
  - 0.0
  - 0.0
  slope_treshold: 0.75
simulator:
  _target_: humanoidverse.simulator.isaacgym.isaacgym.IsaacGym
  _recursive_: false
  config:
    name: isaacgym
    terrain: ${terrain}
    plane:
      static_friction: 1.0
      dynamic_friction: 1.0
      restitution: 0.0
    sim:
      fps: 200
      control_decimation: 4
      substeps: 1
      physx:
        num_threads: 4
        solver_type: 1
        num_position_iterations: 4
        num_velocity_iterations: 0
        contact_offset: 0.01
        rest_offset: 0.0
        bounce_threshold_velocity: 0.5
        max_depenetration_velocity: 1.0
        default_buffer_size_multiplier: 5
        contact_collection: 2
domain_rand:
  push_robots: false
  push_interval_s:
  - 5
  - 10
  max_push_vel_xy: 1.0
  randomize_base_com: true
  base_com_range:
    x:
    - -0.1
    - 0.1
    'y':
    - -0.1
    - 0.1
    z:
    - -0.1
    - 0.1
  randomize_link_mass: true
  link_mass_range:
  - 0.7
  - 1.3
  randomize_pd_gain: true
  kp_range:
  - 0.75
  - 1.25
  kd_range:
  - 0.75
  - 1.25
  randomize_friction: true
  friction_range:
  - -0.6
  - 1.2
  randomize_base_mass: false
  randomize_torque_rfi: true
  rfi_lim: 0.1
  randomize_rfi_lim: false
  rfi_lim_range:
  - 0.5
  - 1.5
  randomize_ctrl_delay: false
  ctrl_delay_step_range:
  - 0
  - 3
  added_mass_range:
  - -5.0
  - 10.0
  randomize_link_body_names:
  - pelvis
  - left_hip_yaw_link
  - left_hip_roll_link
  - left_hip_pitch_link
  - left_knee_link
  - right_hip_yaw_link
  - right_hip_roll_link
  - right_hip_pitch_link
  - right_knee_link
  randomize_motion_ref_xyz: true
  motion_ref_xyz_range:
  - - -0.02
    - 0.02
  - - -0.02
    - 0.02
  - - -0.1
    - 0.1
  motion_package_loss: false
  package_loss_range:
  - 1
  - 10
  package_loss_interval_s: 2
  born_offset: false
  born_offset_curriculum: false
  born_offset_level_down_threshold: 50
  born_offset_level_up_threshold: 120
  level_degree: 5.0e-05
  born_distance: 0.25
  born_offset_range:
  - 0.0
  - 1
  born_offset_possibility: 1.0
  born_heading_curriculum: false
  born_heading_randomization: false
  born_heading_level_down_threshold: 50
  born_heading_level_up_threshold: 120
  born_heading_degree: 10
  born_heading_range:
  - 0
  - 180
  born_heading_level_degree: 5.0e-05
rewards:
  set_reward: Yuanhang
  set_reward_date: 20250206
  only_positive_rewards: false
  reward_scales:
    tracking_lin_vel: 1.0
    tracking_ang_vel: 0.5
    penalty_lin_vel_z: -2.0
    penalty_ang_vel_xy: -0.05
    penalty_orientation: -1.0
    penalty_dof_vel: -0.001
    penalty_dof_acc: -2.5e-07
    penalty_action_rate: -0.1
    base_height: -10.0
    penalty_slippage: -1.0
    limits_dof_pos: -5.0
    feet_air_time: 1.0
    penalty_feet_height: -5.0
    feet_heading_alignment: -0.3
    penalty_feet_ori: -1.0
    penalty_close_feet_xy: -2.0
    penalty_hip_pos: -1.0
  reward_tracking_sigma:
    lin_vel: 0.25
    ang_vel: 0.25
  reward_limit:
    soft_dof_pos_limit: 0.9
    soft_dof_vel_limit: 0.9
    soft_torque_limit: 0.9
  locomotion_max_contact_force: 200.0
  desired_feet_max_height_for_this_air: 0.2
  desired_base_height: 0.728
  feet_height_target: 0.2
  close_feet_threshold: 0.15
  reward_penalty_curriculum: true
  reward_initial_penalty_scale: 0.5
  reward_min_penalty_scale: 0.0
  reward_max_penalty_scale: 1.0
  reward_penalty_level_down_threshold: 400
  reward_penalty_level_up_threshold: 700
  reward_penalty_degree: 5.0e-05
  num_compute_average_epl: 10000
  reward_penalty_reward_names:
  - base_height
  - penalty_lin_vel_z
  - penalty_ang_vel_xy
  - penalty_orientation
  - penalty_torques
  - penalty_dof_acc
  - penalty_dof_vel
  - penalty_action_rate
  - penalty_feet_contact_forces
  - penalty_stumble
  - penalty_slippage
  - penalty_feet_ori
  - feet_ori
  - penalty_in_the_air
  - limits_dof_pos
  - limits_dof_vel
  - limits_torque
  - termination
  - feet_air_time
  - feet_max_height_for_this_air
  - penalty_feet_slippage
  - penalty_feet_height
  - penalty_close_feet_xy
  - penalty_close_knees_xy
  - feet_heading_alignment
  - penalty_hip_pos
obs:
  obs_dict:
    actor_obs:
    - base_ang_vel
    - projected_gravity
    - command_lin_vel
    - command_ang_vel
    - dof_pos
    - dof_vel
    - actions
    critic_obs:
    - base_ang_vel
    - projected_gravity
    - command_lin_vel
    - command_ang_vel
    - dof_pos
    - dof_vel
    - actions
  obs_auxiliary:
    history:
      base_ang_vel: 20
      projected_gravity: 20
      dof_pos: 20
      dof_vel: 20
      actions: 20
      command_lin_vel: 20
      command_ang_vel: 20
  obs_scales:
    base_lin_vel: 2.0
    base_ang_vel: 0.25
    projected_gravity: 1.0
    command_lin_vel: 1.0
    command_ang_vel: 1.0
    dof_pos: 1.0
    dof_vel: 0.05
    history: 1.0
    actions: 1.0
  noise_scales:
    base_lin_vel: 0.0
    base_ang_vel: 0.0
    projected_gravity: 0.0
    command_lin_vel: 0.0
    command_ang_vel: 0.0
    dof_pos: 0.0
    dof_vel: 0.0
    actions: 0.0
    history: 0.0
  obs_dims:
    base_lin_vel: 3
    base_ang_vel: 3
    projected_gravity: 3
    command_lin_vel: 2
    command_ang_vel: 1
    dof_pos: 12
    dof_vel: 12
    actions: 12
eval_timestamp: ${now:%Y%m%d_%H%M%S}
eval_name: Playback
eval_log_dir: Playback/${eval_name}/${eval_timestamp}
play: logs/G1TestDeploy/20250730_105719-G112dof_loco_IsaacGym-locomotion-g1_12dof/model_playback_5000.npz
